name: Flyte CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-run:
    runs-on: self-hosted 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Copy workflow files
        run: |
          mkdir -p /flyte-workspace
          cp workflow.py /flyte-workspace/workflow.py
          cp pyproject.toml /flyte-workspace/pyproject.toml
          chmod -R 777 /flyte-workspace

      - name: Install flytekit
        run: |
          uv tool install flytekit

      - name: Activate the venv
        run: |
          uv sync
          source .venv/bin/activate

      - name: Execute Flyte workflow
        run: |
          pyflyte run --remote workflow.py my_workflow --x 5 --y 3
