name: Flyte CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-run:
    runs-on: self-hosted 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          curl -LsSf https://astral.sh/uv/install.sh | sh
          source $HOME/.local/bin/env

      - name: Copy workflow files
        run: |
          mkdir -p $GITHUB_WORKSPACE/flyte-workspace
          cp workflow.py $GITHUB_WORKSPACE/flyte-workspace/workflow.py
          cp pyproject.toml $GITHUB_WORKSPACE/flyte-workspace/pyproject.toml
          chmod -R 777 $GITHUB_WORKSPACE/flyte-workspace

      - name: Install flytekit
        run: |
          uv python install 3.12
          uv tool install flytekit
          flytectl version

      - name: Activate the venv
        run: |
          uv sync
          source .venv/bin/activate

      - name: Execute Flyte workflow
        run: |
          pyflyte run --remote workflow.py my_workflow --x 5 --y 3
